consolidate to one CDK crate
thesimplekid/cashu-crab pull request #81
Opened 2024-04-10 21:56 UTC by thesimplekid

Having the two crates adds complexity without benefit since features can be used instead

2024-04-10 22:09 UTC, thesimplekid commented
@yukibtc  @lorenzolfm @davidcaseria thoughts?

2024-04-10 22:40 UTC, lorenzolfm commented
I agree with this approach. Seems much simpler :)

2024-04-11 07:45 UTC, yukibtc requested changes
Looks good. I found only 2 things to fix

2024-04-11 07:45 UTC, yukibtc commented on .github/workflows/ci.yml
> +            -p cdk --no-default-features --features mint --features redb,
This line should be removed

2024-04-11 07:45 UTC, yukibtc commented on misc/scripts/check-crates.sh
>      "-p cashu"
This should be renamed to `cdk`

2024-04-12 11:54 UTC, merged